
name = "my-next-app"

[runtime]
env = "production"

[define]
"process.env.NODE_ENV" = "'development'"

[env]
NEXT_TELEMETRY_DISABLED = "1"
NEXT_TURBOPACK_TRACING = "1"


[install]
auto = true
exact = true
production = false
prefer = "offline"
registry = "https://registry.npmjs.org"



[resolver]
extensions = [".ts", ".tsx", ".js", ".jsx", ".json"]


[transpiler]
jsx = "automatic"
jsxImportSource = "react"


[test]
smol = true
randomize = true
